### ISSUE TITLE
Widget not updating state when order is successful

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#46]
![screen shot 2018-03-09 at 17 24 28](https://user-images.githubusercontent.com/92292/37217794-cbbe5130-23be-11e8-809d-2c8e8d6814f3.png)

**Comment by ziggamon** [comment]
Same issue applies when the refill is failed. Basically there is no status updates after the above screen

**Comment by wille** [comment]
I'm totally sure this was fixed. I'll try both standalone and in the dashboard with some LTC payments.

**Comment by ziggamon** [comment]
Not fixed, at least not in prod. No need for LTC can do it with regular balance payments as well.

**Comment by wille** [comment]
I've tried live refills on @Maximization phone both locally and live in production and first get `payment confirmed` and then `refill delivered`. I've also tried sending a refill to a random number, and I get to the `refill failed` page.

I've also tried to do the minimum refill for the phone number provided in the screenshot and it shows as delivered.

**Comment by Maximization** [comment]
Maybe we should look into pusher, can someone put the credentials on 1password?
